from abc import ABC, abstractmethod
from pathlib import Path
class AgentAdapter(ABC):
    name = "unknown"
    @abstractmethod
    def detect(self) -> bool: ...
    @abstractmethod
    def discover_sessions(self) -> list[Path]: ...
    @abstractmethod
    def inspect_session(self, path: Path) -> dict: ...
    @abstractmethod
    def parse_session(self, path: Path): ...
